### ISSUE TITLE
Group layers - incremental groups under groups (4h)

### ISSUE THREAD

**Issue by anderserla** [Sundsvallskommun/OpenEMap-WebUserInterface#118]
It would be great to have the ability of multiple group layers nested inside each other.

**Comment by sweco-sebhar** [comment]
Tested this with change in config2.json - need more testing with other configs containing sub groups.

**Comment by anderserla** [comment]
Great!
Tested with debug_all.json, that contains more subgroups. Works fine, with one small issue:
When  checking a layer or sublayer, all its parents should be checked. Now only its first parent gets checked.
![image](https://cloud.githubusercontent.com/assets/5744996/6148526/944854f2-b202-11e4-8aa6-59f415182a53.png)

**Comment by anderserla** [comment]
Another issue to be solved is that the context menu item for adding a group layer should be activated even if the user clicks a group layer, making it possible to add group layers under group layers

**Comment by sweco-sebhar** [comment]
You are right there is no logic that disables the context menu, but there is logic that disables invididual actions that should be displayed in the context menu and I can only assume that when no actions are enabled the context menu will not be showed. There is logic in place that only enables group creation on the root here:

https://github.com/Sundsvallskommun/OpenEMap-WebUserInterface/blob/master/src/main/javascript/view/layer/Advanced.js#L188
