### ISSUE TITLE
Legend - does not work when using group layers (4h?)

### ISSUE THREAD

**Issue by anderserla** [Sundsvallskommun/OpenEMap-WebUserInterface#124]
Do the following
1. Open a map that has a group layer defined and a layer with legend
2. Click on a layer supporting a legend-> legend image shows
3. Turn a layer on/off
4. Click on a layer supporting a legend-> ERROR legend image DONT show

**Comment by anderserla** [comment]
The problem only seems to be when a layer is turned on (checked).

**Comment by sweco-sebhar** [comment]
I have investigated the issue and the conclusion is that the (dynamically created) element that contains the legend is removed from DOM completely when clicking the visibility checkbox. Why this happens is unknown and requires diving deep into GeoExt and Ext JS which makes this issue non-trivial to fix :(

For reference this code toggles visibility on node click:
https://github.com/Sundsvallskommun/OpenEMap-WebUserInterface/blob/master/src/main/javascript/view/layer/Tree.js#L72

For reference this line defines the legend when node is created:
https://github.com/Sundsvallskommun/OpenEMap-WebUserInterface/blob/master/src/main/javascript/view/layer/Tree.js#L72

NOTE: Node legend is only *defined* by Open eMap code - the actual creation is then done by Ext JS and GeoExt.

**Comment by sweco-sebhar** [comment]
Possibly this can be hacked in GeoExt2 WmsLegend. No success yet though.

**Comment by sweco-sebhar** [comment]
No luck. I cannot find out why the element is removed from DOM. It must be fixable but need to rewrite all related code and dive deeper into GeoExt and Ext JS.

**Comment by sweco-sebhar** [comment]
Reworked to show legend as tooltip when clicking the small inline legend.
