### ISSUE TITLE
Print - error handling when WMS-server returns an error (4h)

### ISSUE THREAD

**Issue by anderserla** [Sundsvallskommun/OpenEMap-WebUserInterface#13]
If the underlying WMS-servers return an error, it should be reported to the user in some way.

1. Click the Print tool
2. Choose Pappersformat="A1 liggande", Upplösning="Hög", Skala="1:100000" -> Error when rendering map. Image size too big (cascaded WMS "topowebkartan_nedtonad"). Today it returns a white map.

**Comment by sweco-sebhar** [comment]
Error handling in mapfish is not well defined. It might return an error that can be reported to client but it might also just ignore it and draw the rest of available layers, depends on severity of error. We can investigate if we can handle this specific error (WMS returns error = mapfish should return error).

**Comment by sweco-sebhar** [comment]
Official documentation for MapFish 2.x:

“brokenUrlPlaceholder” the placeholder image to use in the case of a broken url. By default, when a url request fails, an error is thrown and the pdf process terminates."

I can verify that the default is indeed "throw" but the pdf process will *not* terminate as expected/documented. An exception will be thrown and logged that's it. This is the case for both when the WMS server is not responding at all and when the WMS server is returning an error in XML form.

Also noted that settings for connectionTimeout and socketTimeout isn't used at all and surprisingly the `HttpURLConnection` does not seem to care about it anyway (at least in my JVM, OpenJDK 7).

**Comment by sweco-sebhar** [comment]
Patched mapfish-print 2.1.1 here:
https://github.com/sweco/mapfish-print/releases/tag/2.1.1-brokenUrlPlaceholder-throw-really

Source:
https://github.com/sweco/mapfish-print/tree/brokenUrlPlaceholder-throw-really

Will return HTTP 500 and a generic text message that differs depending on timeout or WMS error and perhaps other classes of errors. The actual WMS error in XML form will not be returned (it is buried very far down in the code).

**Comment by anderserla** [comment]
Important to NOT use EXCEPTION=application/vnd.ogc.se_inimage in the WMS-layers, cause that makes Geoserver return a image with the error written in text in it, and MapFish interprets that as no error.

**Comment by sweco-sebhar** [comment]
I've created a PR for this change on the development branch for mapfish-print 2.x - https://github.com/mapfish/mapfish-print/pull/283.
