### ISSUE TITLE
Grunt - make grunt update integrationfiles to point at right OpenEMap.js file (2h)

### ISSUE THREAD

**Issue by anderserla** [Sundsvallskommun/OpenEMap-WebUserInterface#148]
Make "grunt dist" automatically update all *.html files in repo to reflect the dits-name of OpenEMap*.js file

**Comment by sweco-sebhar** [comment]
This would require introducing a html preprocessor which is not unreasonable and available for grunt but I think it would be better to build release without version postfix. That way html-files would always point to the latest release and grunt dist could still produce a zip with version postfix as a release artifact if needed.

Suggested changes:

* compile js and gather all resources into folder /dist
* do not postfix compiled js with version
* zip contents of /dist to OpenEMap-x.x.x.zip and place in /artifacts

**Comment by anderserla** [comment]
Fixed in 1.6.0
