### ISSUE TITLE
Vid dra och släpp visualiseras det inte vart lagret kommer hamna i listan (~8h)

### ISSUE THREAD

**Issue by anderserla** [Sundsvallskommun/OpenEMap-WebUserInterface#18]
Avancerade lagerhanteraren.
När man drar ett lager är det svårt att se vart det hamnar. Inget grönt streck som är standard i ExtJS-temat.

**Comment by sweco-sebhar** [comment]
Har kunnat utreda detta till att bero på temaproblem. Det ser rätt ut i standard Ext JS Neptune tema (men annat ser inte bra ut i Neptune).

**Comment by anderserla** [comment]
Nu syns det i alla fall att man drar ett objekt. Det tror jag inte det gjort tidigare.

**Comment by sweco-sebhar** [comment]
Ok, jag har inte gjort något :)

**Comment by sweco-sebhar** [comment]
Jag ser streck nu. Jag har inte gjort någon medveten ändring för detta men det är kanske ett resultat av justeringar och ombyggnad av temat i samband med åtgärder för #42 (resulterat i ext-theme-oep 1.7.0).
