### ISSUE TITLE
Grouplayers are not correctly serialized (2h)

### ISSUE THREAD

**Issue by sweco-sebhar** [Sundsvallskommun/OpenEMap-WebUserInterface#185]
Noticed when developing #85. It seems loading a serialized config with group layers will create them as WMS base layers.

**Comment by sweco-sebhar** [comment]
Fix in PR #193 (to be merged onto permalink branch since that has not been merged to develop yet)

**Comment by anderserla** [comment]
Fixing parse to read visibility of base layers, to make the right layer visible. OpenLayers assumes that the first baselayer should be used. Therefor needs to sort baselayer on init. 
Adding visibility flags to baselayer config 
6fdcd5e
