### ISSUE TITLE
Zoom to scale (~4h)

### ISSUE THREAD

**Issue by anderserla** [Sundsvallskommun/OpenEMap-WebUserInterface#42]
Text box for the tool "zoom to scale" does not show correct. CSS-problems?

**Comment by anderserla** [comment]
Vad kom du fram till i denna @sweco-seajaa

**Comment by sweco-sebhar** [comment]
Jag tror det är denna https://github.com/Sundsvallskommun/OpenEMap-WebUserInterface/blob/master/src/main/javascript/form/ZoomSelector.js

**Comment by anderserla** [comment]
Varför blir det ojämna skalor? Hur ställer jag det @sweco-sebhar ?

**Comment by sweco-sebhar** [comment]
DPI definition related, I think this is no issue anymore right @anderserla?
