### ISSUE TITLE
Layer control/Legend - more user friendly (~16h)

### ISSUE THREAD

**Issue by anderserla** [Sundsvallskommun/OpenEMap-WebUserInterface#55]
![image](https://cloud.githubusercontent.com/assets/5744996/5899910/cac338fa-a562-11e4-8a8f-2ed40a33a73f.png)
Ändra den avancerade lagerkontrollen så att den fungerar enligt följande:
Mindre teckensnitt för lagernamnen.
Radbrytning för långa lagernamn.

”Visas på kartan” + Sopkorg + Laddar
-	Sopkorg för att ta bort lager (Avancerad lagerkontroll)
o	Dra lager till papperskorg för att ta bort det
-	Symbol som snurrar visar att lager laddas
-	Dra lager upp/ner för att ändra ritordning, och för att flytta det i lagerstrukturen
o	Visa var lagret hamnar när man släpper det
o	Kontrollera status för eventuella överordnade grupplager som lagret flyttas från/till och tänd/släck dem

Grupplager
-	+/- + Namn + Antal tända/totalt antal + i
-	+/- framför grupplagret för att expandera/kollapsa det
-	Tänd/släck alla underlager genom att klicka på checkboxen/lagernamnet
o	Mörkt tema om alla lager är släckta
o	Ljust tema om något lager är tänt
o	Om alla underlager släcks, så släcks även grupplagret
o	Radbrytniung om namnet är för långt
-	Namn med liten stil
-	”i” visas enbart om metadata finns för lagret (Avancerad lagerkontroll)
o	Klick på ”i” visar metadata
-	Status
o	Expanderat = ja/nej
o	Tänt = ja/nej (kontrollera mot underlager vid initiering)
o	Antal tända underlager
o	Antal underlager
o	Laddas = ja/nej
	Visas genom att lagernamnet får grå färg tills det är laddat

Kartlager
-	Teckenförklaring + Namn + i
-	Teckenförklaring
o	Visa teckenförklaring framför lagernamn
o	Om teckenförklaring innehåller fler symboler (är stor?)
	Klick på teckenförklaring expanderar/kollapsar större teckenförklaring under lagernamnet
-	Tänd/släck lager genom att klicka på checkbox/lagernamnet
o	Mörkt tema om lagret är släckt
o	Ljust tema om lagret är tänt
o	Radbrytning om namnet är för långt
-	Namn med liten stil
-	”i” visas enbart om metadata finns för lagret (Avancerad lagerkontroll)
o	Klick på ”i” visar metadata
-	Status
o	Tänt = ja/nej (kontrollera mot överordnat grupplager vid initiering)
o	Expanderad teckenförklaring = ja/nej
o	Laddas = ja/nej
	Visas genom att lagernamnet får grå färg tills det är laddat

**Comment by anderserla** [comment]
See new use case for layer control.

**Comment by sweco-sebhar** [comment]
Det går bra att lägga till lager på rootnivån utan att rootnoden syns. Det är dock svårt att se för användaren pga. #18 som beror på temaproblem (ser rätt ut i standard Ext JS Neptune tema).

**Comment by sweco-sebhar** [comment]
Implementation kan följas i #162.

**Comment by sweco-sebhar** [comment]
Har kunnat justera stil för att spara plats. 

Har försökt hitta rätt sätt att hantera legendbilder för att få det som önskat och kommer fram till att det kanske inte är omöjligt men väldigt komplext att manipulera detta. Osäkert om det går att få det bra för lager som har flera regler (och därmed större legendbild). Behöver sannolikt ytterligare ca en arbetsdag för en första implementation.

**Comment by sweco-sebhar** [comment]
Skapat hack för inline legend med skalning så att de alltid passar 20x20px.

Radbryt för lagernamn verkar tyvärr svårt att åstadkomma.

Kvarvarande att-göra-lista:

* [ ] hantera då legendbild inte kan hämtas
* [ ] ta bort checkboxar på lager i "lägg till lager"-lista
* [ ] indentera utfälld fullständig legend (svårt)
* [ ] flytta sopkorg till titel och drag&drop till den (risk att det inte går att få klart i tid)
* [ ] laddningsindikator (svårt)
* [ ] radbryt för lagernamn (svårt)

**Comment by anderserla** [comment]
Sorterade listan med kvarvarande punkter i ovenstående kommentar. Beta av dem uppifrån. Flytta sopkorg och laddningsindikator kan prioriteras bort om det blir tidsbrist.

**Comment by anderserla** [comment]
Kollade på lösningen och jag tycker den är snygg. Jag kommer att visa den på morgondagens avstämningsmöte med beställaren. Åtgärdar du bara punkt 1 ovan, så tror jag lösningen kan accepteras. Men det vore som sagt bra om de fyra översta gick att lösa. Jag lade till ytterligare två småpunkter i din att-göra lista

**Comment by anderserla** [comment]
Bra jobbat Björn, nu funkar det som det ska i Chrome, IE9 och Firefox. Timeouten kommer vi nog att behöva ta bort, men annars ser det kanon ut! Får se vad användarna tycker...

**Comment by anderserla** [comment]
Stänger denna, då all restpunkter brutits ut som egna issues.
