### ISSUE TITLE
Avklippt text i sökruta (2h)

### ISSUE THREAD

**Issue by patrik1** [Sundsvallskommun/OpenEMap-WebUserInterface#69]
Vid sökning efter adress visas adressen dåligt. Inte hela adressen syns, texten är avklippt i underkant. Gäller endast Firefox.
![bilaga 2](https://cloud.githubusercontent.com/assets/7370134/3088542/cf64a1c0-e571-11e3-9887-b30a9444f209.png)

**Comment by anderserla** [comment]
Fixed in Sundsvallskommun/ext-theme-oep
