### ISSUE TITLE
Layer control - layers without legend (1h)

### ISSUE THREAD

**Issue by patrik1** [Sundsvallskommun/OpenEMap-WebUserInterface#71]
När man klickar på texten i ett informationslager på topnivå som inte har några undernivåer hoppar texten ner och det blir ett märkligt melanrum i listan. Se bifigad bild, där texten "Fastighetsgränser" klickats på.
![bilaga 3](https://cloud.githubusercontent.com/assets/7370134/3088555/04175a70-e572-11e3-8b24-efbcbf277300.png)

**Comment by sweco-sebhar** [comment]
Fungerar det inte att lägga till statisk teckenförklaring?

**Comment by anderserla** [comment]
Not a problem anymore, since we changed the legend handling, to use popups.
