### ISSUE TITLE
Länk i nytt fönster

### ISSUE THREAD

**Issue by sweco-sepefa** [Sundsvallskommun/OpenEMap-WebUserInterface#82]
När man klickar på en länk genom informationsverktyget ska länken öppnas i ett nytt fönster.

**Comment by anderserla** [comment]
Fixing parse to read visibility of base layers, to make the right layer visible. OpenLayers assumes that the first baselayer should be used. Therefor needs to sort baselayer on init. 
Adding visibility flags to baselayer config 
6fdcd5e2b783ee8875bda038c2691e1b6f413a36
